# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([169,  28,  78,   3, 119, 186,  61,  60,  71, 175, 186,  98])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[ 85,  53, 144,  16],
       [ 67, 182, 137,  17],
       [130,  49, 148, 112]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[ 91,  67, 100, 145,  34, 147],
        [140, 191,  59,  62, 113, 109],
        [174,  18,   3, 121,  53,  50]],

       [[113,  58, 108,  63,   6,  58],
        [ 90, 133,  67, 151,  93, 184],
        [ 19,  26,  23,  56,  72,  13]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1,  28,  78,   3, 119, 186,  61,  60,  71, 175, 186,  98])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[ 85,  53, 144,  16],
       [ 67, 182,  -1,  17],
       [130,  49, 148, 112]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[ 91,  67, 100, 145,  34, 147],
        [140, 191,  59,  62, 113, 109],
        [174,  18,   3, 121,  53,  50]],

       [[113,  58, 108,  63,   6,  58],
        [ 90, 133,  67, 151,  93, 184],
        [ 19,  26,  23,  56,  -1,  13]]])

In [8]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
print(a1D[0])
a1D_modificado

-1


array([ -1,  28,  78,   3, 119, 186,  61,  60,  71, 175, 186,  98, 100,
       130])

In [9]:
a1D # a1D não foi modificado

array([ -1,  28,  78,   3, 119, 186,  61,  60,  71, 175, 186,  98])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([ 85,  53, 144,  16,  67, 182,  -1,  17, 130,  49, 148, 112, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[ 85,  53, 144,  16],
       [ 67, 182,  -1,  17],
       [130,  49, 148, 112]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([ 91,  67, 100, 145,  34, 147, 140, 191,  59,  62, 113, 109, 174,
        18,   3, 121,  53,  50, 113,  58, 108,  63,   6,  58,  90, 133,
        67, 151,  93, 184,  19,  26,  23,  56,  -1,  13, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[ 91,  67, 100, 145,  34, 147],
        [140, 191,  59,  62, 113, 109],
        [174,  18,   3, 121,  53,  50]],

       [[113,  58, 108,  63,   6,  58],
        [ 90, 133,  67, 151,  93, 184],
        [ 19,  26,  23,  56,  -1,  13]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1  28  78   3 119 186  61  60  71 175 186  98 100 130]
[ 78 119 186  61  60  71 175 186  98 100 130]
