In [1]:
# Importando o NumPy
import numpy as np

In [2]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [5]:
percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


In [21]:
arr=np.eye(5)
# arr[arr == 0] = -1 # OK
# arr[arr != 1] = -1 # OK
# arr = np.full((5x5),-1) # NOK
# arr = arr - (np.eye(5) + 1) # NOK

arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')


[ True False False  True False False False]


In [25]:
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
# arr[arr % 2 == 0] = -1 # OK 
# arr[::2] = -1 # OK
# arr[1::2] = -1 # NOK
# arr[-2::-2] = -1 # OK

arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])