# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Comparação entre arrays

In [2]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [3]:
c1D = np.random.randint(1,10,20)
c1D

array([5, 2, 8, 4, 7, 8, 6, 9, 3, 5, 5, 9, 8, 5, 5, 2, 1, 9, 4, 6])

In [4]:
c1D == 5

array([ True, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True,  True, False, False, False,
       False, False])

In [5]:
c1D[c1D == 5]

array([5, 5, 5, 5, 5])

### Operações entre arrays e escalares

In [6]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [10]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [11]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [12]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [13]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [14]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [15]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [16]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [17]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [18]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [19]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [20]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [21]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [22]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [23]:
np.remainder(c1D, a1D)

array([0, 0, 0, 0, 0])

In [24]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
raiz1D = np.sqrt(g1D)

raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [26]:
str=np.full(3,'-')
str 

array(['-', '-', '-'], dtype='<U1')

In [27]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[46, 83, 87, 92, 89, 92,  3, 29, 29, 79],
       [14, 62, 17, 45, 13, 78, 70, 16, 21, 50],
       [39, 79, 68, 35, 84, 47, 51, 29, 37,  8],
       [76,  9, 22,  5, 11, 65, 71, 70, 32, 56],
       [89, 62, 27, 86, 86, 38, 66, 24, 83, 52]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [28]:
# Soma de todos os elementos
d2D.sum()

2522

In [29]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([264, 295, 221, 263, 283, 320, 261, 168, 202, 245])

In [30]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([629, 386, 477, 417, 613])

In [31]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([264, 295, 221, 263, 283, 320, 261, 168, 202, 245])

In [32]:
# Retorna o menor valor geral
d2D.min()

3

In [33]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([14,  9, 17,  5, 11, 38,  3, 16, 21,  8])

In [34]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([ 3, 13,  8,  5, 24])

In [35]:
# Retorna o maior valor geral
d2D.max()

92

In [36]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([89, 83, 87, 92, 89, 92, 71, 70, 83, 79])

In [37]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([92, 78, 84, 76, 89])

In [38]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  46,  129,  216,  308,  397,  489,  492,  521,  550,  629,  643,
        705,  722,  767,  780,  858,  928,  944,  965, 1015, 1054, 1133,
       1201, 1236, 1320, 1367, 1418, 1447, 1484, 1492, 1568, 1577, 1599,
       1604, 1615, 1680, 1751, 1821, 1853, 1909, 1998, 2060, 2087, 2173,
       2259, 2297, 2363, 2387, 2470, 2522])

In [39]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 46,  83,  87,  92,  89,  92,   3,  29,  29,  79],
       [ 60, 145, 104, 137, 102, 170,  73,  45,  50, 129],
       [ 99, 224, 172, 172, 186, 217, 124,  74,  87, 137],
       [175, 233, 194, 177, 197, 282, 195, 144, 119, 193],
       [264, 295, 221, 263, 283, 320, 261, 168, 202, 245]])

In [40]:
d2D

array([[46, 83, 87, 92, 89, 92,  3, 29, 29, 79],
       [14, 62, 17, 45, 13, 78, 70, 16, 21, 50],
       [39, 79, 68, 35, 84, 47, 51, 29, 37,  8],
       [76,  9, 22,  5, 11, 65, 71, 70, 32, 56],
       [89, 62, 27, 86, 86, 38, 66, 24, 83, 52]])

In [41]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 46, 129, 216, 308, 397, 489, 492, 521, 550, 629],
       [ 14,  76,  93, 138, 151, 229, 299, 315, 336, 386],
       [ 39, 118, 186, 221, 305, 352, 403, 432, 469, 477],
       [ 76,  85, 107, 112, 123, 188, 259, 329, 361, 417],
       [ 89, 151, 178, 264, 350, 388, 454, 478, 561, 613]])

In [42]:
# Retorna a média aritmética
d2D.mean()

50.44

In [43]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([52.8, 59. , 44.2, 52.6, 56.6, 64. , 52.2, 33.6, 40.4, 49. ])

In [44]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([62.9, 38.6, 47.7, 41.7, 61.3])

In [45]:
# Retorna o desvio padrão
d2D.std()

27.809466014290887

In [46]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([26.79850742, 26.43482551, 28.02427519, 32.56132675, 36.45600088,
       19.72815247, 25.62342678, 18.81063529, 21.92350337, 22.97825059])

In [47]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([31.29041387, 24.09232243, 22.35643084, 27.24720169, 23.82876413])

In [48]:
# Retorna a mediana (geral)
np.median(d2D)

50.5

In [49]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([46., 62., 27., 45., 84., 65., 66., 29., 32., 52.])

In [50]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([81., 33., 43., 44., 64.])

### Copiando e concatenando arrays

In [51]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[45, 49, 15, 43, 13],
       [35, 19, 27, 15, 38],
       [19, 13, 27, 19,  2],
       [ 7, 43, 23, 41,  3]])

In [52]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[88, 67, 75, 63, 82],
       [94, 61, 50, 83, 62],
       [50, 82, 74, 67, 69],
       [91, 88, 69, 90, 96]])

In [53]:
c2D = a2D
c2D

array([[45, 49, 15, 43, 13],
       [35, 19, 27, 15, 38],
       [19, 13, 27, 19,  2],
       [ 7, 43, 23, 41,  3]])

In [54]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[45, 49, -1, 43, -1],
       [35, -1, 27, -1, 38],
       [-1, -1, 27, -1, -1],
       [-1, 43, 23, 41, -1]])

In [55]:
a2D 

array([[45, 49, -1, 43, -1],
       [35, -1, 27, -1, 38],
       [-1, -1, 27, -1, -1],
       [-1, 43, 23, 41, -1]])

Os elementos de a2D também foram alterados. :-(

In [56]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[ 9, 28, 45,  6, 26],
       [46,  3, 10, 15, 26],
       [ 7, 19,  5, 44, 47],
       [ 3, 46, 10,  1, 38]])

In [57]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[ 9, 28, 45,  6, 26],
       [46,  3, 10, 15, 26],
       [ 7, 19,  5, 44, 47],
       [ 3, 46, 10,  1, 38]])

In [58]:
c2D[c2D < 20] = -1
c2D

array([[-1, 28, 45, -1, 26],
       [46, -1, -1, -1, 26],
       [-1, -1, -1, 44, 47],
       [-1, 46, -1, -1, 38]])

In [59]:
a2D

array([[ 9, 28, 45,  6, 26],
       [46,  3, 10, 15, 26],
       [ 7, 19,  5, 44, 47],
       [ 3, 46, 10,  1, 38]])

Agora sim!!!

### Ordenando os elementos de um array

In [60]:
a1D = np.random.randint(1,100, 15)
a1D

array([25, 35, 85, 54, 70, 34, 23, 85, 65,  2, 91, 46, 18, 94, 70])

In [61]:
a1D.sort()
a1D

array([ 2, 18, 23, 25, 34, 35, 46, 54, 65, 70, 70, 85, 85, 91, 94])

In [62]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[34, 12, 66, 67, 12, 59, 26,  7, 91, 67],
       [67, 87, 29, 64, 88, 62, 27, 65, 40, 84],
       [69, 51, 85, 52, 25, 71,  5, 65, 18,  2],
       [92,  8, 17, 29, 67, 44, 76, 48, 15, 62],
       [64,  9, 17, 94, 10, 66, 69, 94, 98, 53],
       [30, 98, 42, 45, 32, 75, 52, 10,  8, 29]])

In [63]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[ 7, 12, 12, 26, 34, 59, 66, 67, 67, 91],
       [27, 29, 40, 62, 64, 65, 67, 84, 87, 88],
       [ 2,  5, 18, 25, 51, 52, 65, 69, 71, 85],
       [ 8, 15, 17, 29, 44, 48, 62, 67, 76, 92],
       [ 9, 10, 17, 53, 64, 66, 69, 94, 94, 98],
       [ 8, 10, 29, 30, 32, 42, 45, 52, 75, 98]])

In [64]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 2,  5, 12, 25, 32, 42, 45, 52, 67, 85],
       [ 7, 10, 17, 26, 34, 48, 62, 67, 71, 88],
       [ 8, 10, 17, 29, 44, 52, 65, 67, 75, 91],
       [ 8, 12, 18, 30, 51, 59, 66, 69, 76, 92],
       [ 9, 15, 29, 53, 64, 65, 67, 84, 87, 98],
       [27, 29, 40, 62, 64, 66, 69, 94, 94, 98]])

In [65]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[11, 64, 66, 66, 90,  4, 58, 54, 10, 74],
       [73, 19, 52,  6, 35, 48, 14,  7, 82, 96],
       [74,  1, 39, 46, 27, 61, 92, 82, 14,  4],
       [50, 91, 71, 78, 46, 81, 76, 79, 33, 79],
       [64, 84, 20, 14,  9, 35, 40, 31, 81, 76],
       [95, 27, 59, 24, 22, 58, 44,  3,  5, 83]])

In [66]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 4, 10, 11, 54, 58, 64, 66, 66, 74, 90],
       [ 6,  7, 14, 19, 35, 48, 52, 73, 82, 96],
       [ 1,  4, 14, 27, 39, 46, 61, 74, 82, 92],
       [33, 46, 50, 71, 76, 78, 79, 79, 81, 91],
       [ 9, 14, 20, 31, 35, 40, 64, 76, 81, 84],
       [ 3,  5, 22, 24, 27, 44, 58, 59, 83, 95]])

### Transposição de arrays

In [67]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [71]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [72]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [73]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [74]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [75]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [76]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [77]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [78]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [79]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[70,  9, 86,  2,  7, 54, 35, 85, 19],
       [53, 97, 62, 36, 71, 56, 65, 23, 99],
       [92, 26,  5,  1, 52, 45, 51, 78, 23]])

In [80]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[19, 36, 60, 30, 57, 56, 23, 91, 13],
       [27, 71, 98, 16, 94, 84, 13, 87,  3],
       [19, 63, 75, 12, 22, 42, 13, 23, 85],
       [84, 74, 59, 42, 63, 44, 32, 10, 26],
       [72,  6, 24, 60, 57, 89, 23, 43, 98]])

In [81]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[52, 32, 93, 59],
       [27, 35, 18, 82],
       [81, 57, 68, 91],
       [65, 75, 21, 85],
       [37, 51, 53, 81]])

In [82]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [83]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [84]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]]

b2D
[[19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

Concatenação
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]


In [85]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]]

b2D
[[19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

Concatenação
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]


In [86]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

c2D
[[52 32 93 59]
 [27 35 18 82]
 [81 57 68 91]
 [65 75 21 85]
 [37 51 53 81]]

Concatenação
[[19 36 60 30 57 56 23 91 13 52 32 93 59]
 [27 71 98 16 94 84 13 87  3 27 35 18 82]
 [19 63 75 12 22 42 13 23 85 81 57 68 91]
 [84 74 59 42 63 44 32 10 26 65 75 21 85]
 [72  6 24 60 57 89 23 43 98 37 51 53 81]]


In [87]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

c2D
[[52 32 93 59]
 [27 35 18 82]
 [81 57 68 91]
 [65 75 21 85]
 [37 51 53 81]]

Concatenação
[[19 36 60 30 57 56 23 91 13 52 32 93 59]
 [27 71 98 16 94 84 13 87  3 27 35 18 82]
 [19 63 75 12 22 42 13 23 85 81 57 68 91]
 [84 74 59 42 63 44 32 10 26 65 75 21 85]
 [72  6 24 60 57 89 23 43 98 37 51 53 81]]


### Dividindo arrays

In [88]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

1a parte
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]]

2a parte
[[27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]


In [89]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

1a parte
[[70  9 86]
 [53 97 62]
 [92 26  5]
 [19 36 60]
 [27 71 98]
 [19 63 75]
 [84 74 59]
 [72  6 24]]

2a parte
[[ 2  7 54]
 [36 71 56]
 [ 1 52 45]
 [30 57 56]
 [16 94 84]
 [12 22 42]
 [42 63 44]
 [60 57 89]]

3a parte
[[35 85 19]
 [65 23 99]
 [51 78 23]
 [23 91 13]
 [13 87  3]
 [13 23 85]
 [32 10 26]
 [23 43 98]]


In [93]:
# Usa np.where para encontrar índices onde os valores são maiores que 20
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print("Array original")
print(arr)
print("")
print("Retorno")
print(np.where(arr > 20))
print("-"*50)

print("Array original")
print(A)
print("")
print("Retorno")
print(np.where(A > 20))

Array original
[10 15 20 25 30 35 40]

Retorno
(array([3, 4, 5, 6]),)
--------------------------------------------------
Array original
[[70  9 86  2  7 54 35 85 19]
 [53 97 62 36 71 56 65 23 99]
 [92 26  5  1 52 45 51 78 23]
 [19 36 60 30 57 56 23 91 13]
 [27 71 98 16 94 84 13 87  3]
 [19 63 75 12 22 42 13 23 85]
 [84 74 59 42 63 44 32 10 26]
 [72  6 24 60 57 89 23 43 98]]

Retorno
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
       6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7]), array([0, 2, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 4, 5, 6, 7, 8, 1,
       2, 3, 4, 5, 6, 7, 0, 1, 2, 4, 5, 7, 1, 2, 4, 5, 7, 8, 0, 1, 2, 3,
       4, 5, 6, 8, 0, 2, 3, 4, 5, 6, 7, 8]))


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array original")
print(arr)
print("")
print("Retorno")
print(np.where(arr % 2 == 0, None, arr))

Array original
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Retorno
[[1 None 3]
 [None 5 None]
 [7 None 9]]
