# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([1, 5, 3, 2, 2, 6, 3, 7, 0, 3])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[26, 84, 97, 64, 16],
       [65, 66,  4, 72, 78],
       [ 9, 84, 10,  7, 65],
       [20, 78, 16, 37, 52]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.5086925 , 0.15986613, 0.00597175, 0.7648458 , 0.99459523],
        [0.03633579, 0.85987435, 0.36232955, 0.53028985, 0.52738728],
        [0.28771774, 0.64504555, 0.81583586, 0.13394591, 0.26228606],
        [0.88355842, 0.8226261 , 0.92958853, 0.59805212, 0.86038053]],

       [[0.20686888, 0.71140146, 0.68311579, 0.22577533, 0.27459257],
        [0.58671391, 0.38242761, 0.75297763, 0.61614704, 0.48167685],
        [0.648023  , 0.15250288, 0.1060806 , 0.42712801, 0.74372286],
        [0.34040163, 0.08097057, 0.32351311, 0.53589959, 0.56510892]],

       [[0.37624828, 0.09584843, 0.19021274, 0.6059849 , 0.29720923],
        [0.71373814, 0.40279713, 0.65034865, 0.53950666, 0.40114648],
        [0.04762151, 0.51654816, 0.06451739, 0.05755493, 0.96653317],
        [0.04866098, 0.73716089, 0.20184371, 0.89109822, 0.29297616]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int64')

In [21]:
a1D.dtype.name

'int64'

In [22]:
a2D.dtype

dtype('int64')

In [23]:
a2D.dtype.name

'int64'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'