# Indexação e fatiamento (slicing)

In [5]:
# Importando o NumPy
import numpy as np

In [164]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([9, 8, 1, 7, 2, 4, 1, 7, 7, 6])

In [165]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[33,  3, 38, 24, 54],
       [52,  3, 28, 44, 69],
       [81, 54, 90, 77,  7],
       [75, 61, 14,  3, 75]])

In [166]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.78182908, 0.00526454, 0.55334328, 0.30343627, 0.24116351],
        [0.48522443, 0.72478981, 0.49533075, 0.39646813, 0.66120136],
        [0.87634293, 0.827534  , 0.59725808, 0.68958905, 0.81873582],
        [0.92441861, 0.93775054, 0.34351565, 0.04690492, 0.66856275]],

       [[0.76256688, 0.67175544, 0.92580279, 0.88290847, 0.22647062],
        [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
        [0.61084272, 0.38595687, 0.42572998, 0.22653038, 0.73062669],
        [0.2707424 , 0.04596892, 0.58214523, 0.9265451 , 0.54401682]],

       [[0.22941064, 0.46697791, 0.70405032, 0.21585575, 0.62333657],
        [0.83265928, 0.25485005, 0.00846545, 0.74258178, 0.44064677],
        [0.92633292, 0.66650543, 0.51859941, 0.16635793, 0.00954166],
        [0.16692921, 0.68542973, 0.08175751, 0.38645968, 0.44341854]]])

In [14]:
np.random.randn()

-0.06316986241555143

### Acessando elementos específicos

In [167]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([9, 8, 1, 7, 2, 4, 1, 7, 7, 6])

In [168]:
# nome_do_array[índice]
a1D[0]

9

In [169]:
a1D[2]

1

In [170]:
a1D[-1]

6

In [171]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([7, 9, 6])

In [172]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[33,  3, 38, 24, 54],
       [52,  3, 28, 44, 69],
       [81, 54, 90, 77,  7],
       [75, 61, 14,  3, 75]])

In [173]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

28

In [174]:
a2D[3][4]

75

In [175]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([33,  3, 90,  3])

In [176]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([24, 28, 54, 75])

In [177]:
print(a2D)
a2D[:, 0]


[[33  3 38 24 54]
 [52  3 28 44 69]
 [81 54 90 77  7]
 [75 61 14  3 75]]


array([33, 52, 81, 75])

In [178]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([ 3, 90,  3, 33])

In [179]:
a2D[:,[0,1,2,0]] 

array([[33,  3, 38, 33],
       [52,  3, 28, 52],
       [81, 54, 90, 81],
       [75, 61, 14, 75]])

In [180]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[52,  3, 28, 52],
       [33,  3, 38, 33],
       [52,  3, 28, 52],
       [33,  3, 38, 33]])

In [181]:
a2D

array([[33,  3, 38, 24, 54],
       [52,  3, 28, 44, 69],
       [81, 54, 90, 77,  7],
       [75, 61, 14,  3, 75]])

In [182]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[52,  3, 28, 52],
       [33,  3, 38, 33],
       [52,  3, 28, 52],
       [33,  3, 38, 33]])

In [183]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.78182908, 0.00526454, 0.55334328, 0.30343627, 0.24116351],
        [0.48522443, 0.72478981, 0.49533075, 0.39646813, 0.66120136],
        [0.87634293, 0.827534  , 0.59725808, 0.68958905, 0.81873582],
        [0.92441861, 0.93775054, 0.34351565, 0.04690492, 0.66856275]],

       [[0.76256688, 0.67175544, 0.92580279, 0.88290847, 0.22647062],
        [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
        [0.61084272, 0.38595687, 0.42572998, 0.22653038, 0.73062669],
        [0.2707424 , 0.04596892, 0.58214523, 0.9265451 , 0.54401682]],

       [[0.22941064, 0.46697791, 0.70405032, 0.21585575, 0.62333657],
        [0.83265928, 0.25485005, 0.00846545, 0.74258178, 0.44064677],
        [0.92633292, 0.66650543, 0.51859941, 0.16635793, 0.00954166],
        [0.16692921, 0.68542973, 0.08175751, 0.38645968, 0.44341854]]])

In [184]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.21585574697818832

In [185]:
a3D[0][3][1]

0.9377505416765125

### Fatiamento (slicing)

In [186]:
# Array de 1 dimensão
a1D

array([9, 8, 1, 7, 2, 4, 1, 7, 7, 6])

In [187]:
a = a1D[1:5] # Índice 1 ao 4
a

array([8, 1, 7, 2])

In [188]:
b = a1D[0:6] # Índice 0 ao 5
b

array([9, 8, 1, 7, 2, 4])

In [189]:
c = a1D[:6] # Do início ao 5
c

array([9, 8, 1, 7, 2, 4])

In [190]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([9, 1, 2, 1, 7])

In [191]:
e = a1D[-1::-1] # Do final até o início
e

array([6, 7, 7, 1, 4, 2, 7, 1, 8, 9])

In [192]:
# Array de 2 dimensões
a2D

array([[33,  3, 38, 24, 54],
       [52,  3, 28, 44, 69],
       [81, 54, 90, 77,  7],
       [75, 61, 14,  3, 75]])

In [193]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([33,  3, 38, 24, 54])

In [194]:
linha1 = a2D[0,:] # Todos os elementos da linha 1
linha1

array([33,  3, 38, 24, 54])

In [195]:
linha2 = a2D[0,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([ 3, 38, 24])

In [211]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
print(a2D[:][3])
print(a2D[3])
print(a2D[:][:][3])
linha3

[75 61 14  3 75]
[75 61 14  3 75]
[75 61 14  3 75]


array([75, 61, 14,  3, 75])

In [197]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([38, 28, 90, 14])

In [198]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([44, 77,  3])

In [199]:
# Array de 3 dimensões
a3D

array([[[0.78182908, 0.00526454, 0.55334328, 0.30343627, 0.24116351],
        [0.48522443, 0.72478981, 0.49533075, 0.39646813, 0.66120136],
        [0.87634293, 0.827534  , 0.59725808, 0.68958905, 0.81873582],
        [0.92441861, 0.93775054, 0.34351565, 0.04690492, 0.66856275]],

       [[0.76256688, 0.67175544, 0.92580279, 0.88290847, 0.22647062],
        [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
        [0.61084272, 0.38595687, 0.42572998, 0.22653038, 0.73062669],
        [0.2707424 , 0.04596892, 0.58214523, 0.9265451 , 0.54401682]],

       [[0.22941064, 0.46697791, 0.70405032, 0.21585575, 0.62333657],
        [0.83265928, 0.25485005, 0.00846545, 0.74258178, 0.44064677],
        [0.92633292, 0.66650543, 0.51859941, 0.16635793, 0.00954166],
        [0.16692921, 0.68542973, 0.08175751, 0.38645968, 0.44341854]]])

In [200]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.76256688, 0.67175544, 0.92580279, 0.88290847, 0.22647062],
       [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
       [0.61084272, 0.38595687, 0.42572998, 0.22653038, 0.73062669],
       [0.2707424 , 0.04596892, 0.58214523, 0.9265451 , 0.54401682]])

In [201]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.67175544, 0.92580279, 0.88290847],
       [0.88843636, 0.15565039, 0.82424436],
       [0.38595687, 0.42572998, 0.22653038]])

In [202]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.87634293, 0.827534  , 0.59725808, 0.68958905, 0.81873582])

In [203]:
a3D

array([[[0.78182908, 0.00526454, 0.55334328, 0.30343627, 0.24116351],
        [0.48522443, 0.72478981, 0.49533075, 0.39646813, 0.66120136],
        [0.87634293, 0.827534  , 0.59725808, 0.68958905, 0.81873582],
        [0.92441861, 0.93775054, 0.34351565, 0.04690492, 0.66856275]],

       [[0.76256688, 0.67175544, 0.92580279, 0.88290847, 0.22647062],
        [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
        [0.61084272, 0.38595687, 0.42572998, 0.22653038, 0.73062669],
        [0.2707424 , 0.04596892, 0.58214523, 0.9265451 , 0.54401682]],

       [[0.22941064, 0.46697791, 0.70405032, 0.21585575, 0.62333657],
        [0.83265928, 0.25485005, 0.00846545, 0.74258178, 0.44064677],
        [0.92633292, 0.66650543, 0.51859941, 0.16635793, 0.00954166],
        [0.16692921, 0.68542973, 0.08175751, 0.38645968, 0.44341854]]])

In [204]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.48522443, 0.72478981, 0.49533075, 0.39646813, 0.66120136],
       [0.50293848, 0.88843636, 0.15565039, 0.82424436, 0.93077215],
       [0.83265928, 0.25485005, 0.00846545, 0.74258178, 0.44064677]])

In [205]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.30343627, 0.39646813, 0.68958905, 0.04690492],
       [0.88290847, 0.82424436, 0.22653038, 0.9265451 ],
       [0.21585575, 0.74258178, 0.16635793, 0.38645968]])

### Indexação com booleanos

In [206]:
a2Db = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2Db

array([[151, 404, 118,  66,  88, 293, 177, 483],
       [403, 267, 439, 254, 451, 444, 395,  93],
       [ 96,  92,  71, 375, 293, 420,  94, 257],
       [ 81,  99, 233, 333,  40, 200,  14,  72],
       [217, 390, 368,   7, 113,  74, 199, 303],
       [114, 141, 294, 476, 263, 133, 477, 440],
       [222,  21, 382, 157,  46, 282, 285, 204],
       [ 26, 356, 141, 284,  52, 152, 278,  70],
       [ 42, 194, 413, 332,  82,  32, 121, 428],
       [135,  48, 245, 125, 285, 364, 460, 223]])

In [207]:
a2Db >= 250

array([[False,  True, False, False, False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True, False],
       [False, False, False,  True,  True,  True, False,  True],
       [False, False, False,  True, False, False, False, False],
       [False,  True,  True, False, False, False, False,  True],
       [False, False,  True,  True,  True, False,  True,  True],
       [False, False,  True, False, False,  True,  True, False],
       [False,  True, False,  True, False, False,  True, False],
       [False, False,  True,  True, False, False, False,  True],
       [False, False, False, False,  True,  True,  True, False]])

In [208]:
a2Db[a2Db >= 250]

array([404, 293, 483, 403, 267, 439, 254, 451, 444, 395, 375, 293, 420,
       257, 333, 390, 368, 303, 294, 476, 263, 477, 440, 382, 282, 285,
       356, 284, 278, 413, 332, 428, 285, 364, 460])

In [209]:
a2Db.mean()

222.4

In [210]:
a2Db[a2Db <= a2Db.mean()]

array([151, 118,  66,  88, 177,  93,  96,  92,  71,  94,  81,  99,  40,
       200,  14,  72, 217,   7, 113,  74, 199, 114, 141, 133, 222,  21,
       157,  46, 204,  26, 141,  52, 152,  70,  42, 194,  82,  32, 121,
       135,  48, 125])