# Aula 3

Qual a diferença entre acessar a2D[:] e a2D

In [1]:
# Importando o NumPy
import numpy as np

a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100

print(a2D)
print()

# Resultados iguais
print(a2D[:][3])
print(a2D[3])
print(a2D[:][:][3])

# logo a2D==a2D[:] and a2D==a2D[:][:] ...


[[38  5  5 46 11]
 [92 81 61 75 80]
 [12  7 81 88 60]
 [27 92  6  2 76]]

[27 92  6  2 76]
[27 92  6  2 76]
[27 92  6  2 76]
