In [5]:
dic = { "MG": {"Capital": "Belo Horizonte", 
               "Cidades": {1:"Contagem", 
                           2:"Luiz de Fora", 
                           3:"Sete Lagoas"}
              },
        "SP": {"Capital": "São Paulo", 
               "Cidades": {1:"Campinas", 
                           2:"Piracicaba",
                           3:"Franca"}
              },
        "RS": {"Capital": "Porto Alegre", 
               "Cidades": {1:"Pelotas", 
                           2:"Gramado", 
                           3:"Canela"}
              } 
      }
dic["MG"]["Cidades"][2] = "Juiz de Fora"
display(dic)

{'MG': {'Capital': 'Belo Horizonte',
  'Cidades': {1: 'Contagem', 2: 'Juiz de Fora', 3: 'Sete Lagoas'}},
 'SP': {'Capital': 'São Paulo',
  'Cidades': {1: 'Campinas', 2: 'Piracicaba', 3: 'Franca'}},
 'RS': {'Capital': 'Porto Alegre',
  'Cidades': {1: 'Pelotas', 2: 'Gramado', 3: 'Canela'}}}

In [6]:
A = [9, 2, 5, 7]
B = [x for x in range(12,21,3)]
A.append(B)
print(A)

[9, 2, 5, 7, [12, 15, 18]]


In [13]:
estrutura_aninhada = ( [1,2,3],(4,5,6,7),[8,9],( [10,11,12], [(13, 14), 15] ) )

estrutura_aninhada[3][1][0][0]

13

In [14]:
from functools import reduce
teste = [1, 9, 8, 2, 3, 7, 6, 4, 5]
print(reduce(lambda n1, n2: n1 if n1 > n2 else n2, teste))

9


In [15]:
def func():
    x = 1
    print(x)

x = 10
func()
print(x)

1
10


In [16]:
x = range(7)
soma = sum(filter(lambda x_i: x_i % 2 == 0, x))
print(soma)

12


In [39]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
# display(A)
display(A[1,:])
display(A[1])
display(A[:][1])
display(A[1,0:])
display(A[1:2,:][0])

array([ 6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])